In [21]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation

In [22]:
n_samples = 6000
input_dim = 784
hidden_dim = 100
output_dim = 10
model = Sequential(name='test1')
model.add(Dense(output_dim=hidden_dim, input_dim=input_dim, name='First_layer'))
model.add(Activation("relu"))
model.add(Dense(output_dim=output_dim, name='Second_layer'))
model.add(Activation('softmax'))

In [23]:
def one_hot_transformer_3(x, n): 
    if type(x) == list:
        x = np.asarray(x, dtype=np.int).reshape(len(x), 1)
    class_ind = [x==class_num for class_num in range(n)]
    o_h = np.asarray(np.hstack(class_ind), dtype=np.float32)
    return o_h 

In [24]:
rng = np.random.RandomState(123)
x = rng.uniform(size=(n_samples, input_dim))
y = rng.randint(low=0, high=10, size=(n_samples, 1))
y = one_hot_transformer_3(y, output_dim)
print (y[:10])

[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [25]:
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
model.fit(x, y, nb_epoch=10, batch_size=32)
loss_and_metrics = model.evaluate(x[:10], y[:10])
print (loss_and_metrics)

Epoch 1/10
6000/6000 [==============================] - 0s - loss: 2.3524 - acc: 0.0953     
Epoch 2/10
6000/6000 [==============================] - 0s - loss: 2.3197 - acc: 0.1087     
Epoch 3/10
6000/6000 [==============================] - 0s - loss: 2.3068 - acc: 0.1108     
Epoch 4/10
6000/6000 [==============================] - 0s - loss: 2.2979 - acc: 0.1232     
Epoch 5/10
6000/6000 [==============================] - 0s - loss: 2.2912 - acc: 0.1242     
Epoch 6/10
6000/6000 [==============================] - 0s - loss: 2.2831 - acc: 0.1355     
Epoch 7/10
6000/6000 [==============================] - 0s - loss: 2.2750 - acc: 0.1422     
Epoch 8/10
6000/6000 [==============================] - 0s - loss: 2.2684 - acc: 0.1520     
Epoch 9/10
6000/6000 [==============================] - 0s - loss: 2.2605 - acc: 0.1562     
Epoch 10/10
10/10 [==============================] - 0s
[2.0456421375274658, 0.40000000596046448]


In [26]:
print model.name

test1


In [57]:
from keras.models import model_from_json
import json

json_string = model.to_json()
print json_string, type(json_string)
json_string = json.loads(json_string)
json_string['model_name'] = 'test_model'
json_string = json.dumps(json_string)

model2 = model_from_json(json_string)
print model2
print model2.name
#dic = json.loads(json_string)
#if not dic.get('model_name', None):
#    dic.update({'model_name': 'test_model'})


{"class_name": "Sequential", "keras_version": "1.0.7", "config": [{"class_name": "Dense", "config": {"W_constraint": null, "b_constraint": null, "name": "First_layer", "output_dim": 100, "activity_regularizer": null, "trainable": true, "init": "glorot_uniform", "bias": true, "input_dtype": "float32", "input_dim": 784, "b_regularizer": null, "W_regularizer": null, "activation": "linear", "batch_input_shape": [null, 784]}}, {"class_name": "Activation", "config": {"activation": "relu", "trainable": true, "name": "activation_5"}}, {"class_name": "Dense", "config": {"W_constraint": null, "b_constraint": null, "name": "Second_layer", "activity_regularizer": null, "trainable": true, "init": "glorot_uniform", "bias": true, "input_dim": null, "b_regularizer": null, "W_regularizer": null, "activation": "linear", "output_dim": 10}}, {"class_name": "Activation", "config": {"activation": "softmax", "trainable": true, "name": "activation_6"}}]} <type 'str'>
sequential_16


In [59]:
print help(model.train_on_batch)

Help on method train_on_batch in module keras.models:

train_on_batch(self, x, y, class_weight=None, sample_weight=None, **kwargs) method of keras.models.Sequential instance
    Single gradient update over one batch of samples.
    
    # Arguments
        x: input data, as a Numpy array or list of Numpy arrays
            (if the model has multiple inputs).
        y: labels, as a Numpy array.
        class_weight: dictionary mapping classes to a weight value,
            used for scaling the loss function (during training only).
        sample_weight: sample weights, as a Numpy array.
    
    # Returns
        Scalar training loss (if the model has no metrics)
        or list of scalars (if the model computes other metrics).
        The attribute `model.metrics_names` will give you
        the display labels for the scalar outputs.

None
