In [11]:
import numpy as np
import pandas as pd

In [16]:
pcba_file = '/home/xtalpi/bitbucket/mol_data/pcba_deepchem/pcba.csv'
df = pd.read_csv(pcba_file)
df.shape

(439863, 130)

In [17]:
df.head()

PCBA-1030  PCBA-1379  PCBA-1452  PCBA-1454  PCBA-1457  PCBA-1458  \
0        0.0        0.0        NaN        0.0        0.0        0.0   
1        0.0        0.0        NaN        0.0        0.0        NaN   
2        NaN        0.0        NaN        0.0        0.0        0.0   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        0.0        NaN        NaN   

   PCBA-1460  PCBA-1461  PCBA-1468  PCBA-1469  \
0        0.0        0.0        0.0        0.0   
1        0.0        0.0        0.0        0.0   
2        0.0        0.0        0.0        0.0   
3        NaN        NaN        NaN        NaN   
4        NaN        0.0        0.0        0.0   

                         ...                          PCBA-914  PCBA-915  \
0                        ...                               NaN       NaN   
1                        ...                               NaN       NaN   
2                        ...                               NaN       NaN   
3                        ...                               NaN       NaN   
4                        ...                               NaN       NaN   

   PCBA-924  PCBA-925  PCBA-926  PCBA-927  PCBA-938  PCBA-995       mol_id  \
0       NaN       NaN       NaN       NaN       NaN       NaN   CID1511280   
1       NaN       NaN       NaN       NaN       NaN       NaN    CID332939   
2       NaN       NaN       NaN       NaN       NaN       NaN   CID3800322   
3       NaN       NaN       NaN       NaN       NaN       NaN  CID46904422   
4       NaN       NaN       NaN       NaN       NaN       NaN  CID16445987   

                                              smiles  
0               CC(=O)N1CCC2(CC1)NC(=O)N(c1ccccc1)N2  
1                         N#Cc1nnn(-c2ccc(Cl)cc2)c1N  
2      COC(=O)c1ccc(NC(=O)c2ccccc2CC[N+](=O)[O-])cc1  
3            CCC1NC(=O)c2cccnc2-n2c1nc1ccc(F)cc1c2=O  
4  CC1=CC(=O)/C(=C2/C=C(C(=O)Nc3ccc(S(=O)(=O)Nc4o...  

[5 rows x 130 columns]

In [20]:
deepchem_pcba_file = '/home/xtalpi/bitbucket/mol_data/pcba_deepchem/pcba_temp.csv'
df_sub = df.loc[:2000]
df_sub.to_csv(deepchem_pcba_file)

In [15]:
deepchem_df.head()

PCBA-1030  PCBA-1379  PCBA-1452  PCBA-1454  PCBA-1457  PCBA-1458  \
0        0.0        0.0        NaN        0.0        0.0        0.0   
1        0.0        0.0        NaN        0.0        0.0        NaN   
2        NaN        0.0        NaN        0.0        0.0        0.0   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        0.0        NaN        NaN   

   PCBA-1460  PCBA-1461  PCBA-1468  PCBA-1469  \
0        0.0        0.0        0.0        0.0   
1        0.0        0.0        0.0        0.0   
2        0.0        0.0        0.0        0.0   
3        NaN        NaN        NaN        NaN   
4        NaN        0.0        0.0        0.0   

                         ...                          PCBA-914  PCBA-915  \
0                        ...                               NaN       NaN   
1                        ...                               NaN       NaN   
2                        ...                               NaN       NaN   
3                        ...                               NaN       NaN   
4                        ...                               NaN       NaN   

   PCBA-924  PCBA-925  PCBA-926  PCBA-927  PCBA-938  PCBA-995       mol_id  \
0       NaN       NaN       NaN       NaN       NaN       NaN   CID1511280   
1       NaN       NaN       NaN       NaN       NaN       NaN    CID332939   
2       NaN       NaN       NaN       NaN       NaN       NaN   CID3800322   
3       NaN       NaN       NaN       NaN       NaN       NaN  CID46904422   
4       NaN       NaN       NaN       NaN       NaN       NaN  CID16445987   

                                              smiles  
0               CC(=O)N1CCC2(CC1)NC(=O)N(c1ccccc1)N2  
1                         N#Cc1nnn(-c2ccc(Cl)cc2)c1N  
2      COC(=O)c1ccc(NC(=O)c2ccccc2CC[N+](=O)[O-])cc1  
3            CCC1NC(=O)c2cccnc2-n2c1nc1ccc(F)cc1c2=O  
4  CC1=CC(=O)/C(=C2/C=C(C(=O)Nc3ccc(S(=O)(=O)Nc4o...  

[5 rows x 130 columns]

In [ ]:
https://pubchem.ncbi.nlm.nih.gov/pcajax/pcget.cgi?query=download&record_type=datatable&actvty=all&response_type=save&aid=1030

In [3]:
import os
import sys
import numpy as np
import tensorflow as tf
from Erwin.models.tf_utils import tf_core
from Erwin.models.tf_utils import models
from Erwin.models.mlp.mlp import MLP

In [5]:
model = MLP()
model.build(**{'input_dim': 784,
            'hidden_dim': 100,
            'hidden_acti': 'relu',
            'output_dim': 10,
            'output_acti': 'softmax'})

In [6]:
model.output_tensor

<tf.Tensor 'Softmax:0' shape=(?, 10) dtype=float32>

In [9]:
loss = model._compile_loss('categorical_cross_entropy', model.output_tensor, model.labels_tensor, model.weights_tensor)

In [12]:
weights = tf.trainable_variables()
grad = tf.gradients(loss, weights)

In [13]:
print([tf_core.int_shape(w) for w in weights])
print([tf_core.int_shape(g) for g in grad])

[(784, 100), (100,), (100, 10), (10,)]
[(784, 100), (100,), (100, 10), (10,)]


In [15]:
adam = tf.train.AdamOptimizer(learning_rate=0.01)
grads_and_vars = adam.compute_gradients(loss, weights)

In [16]:
grads_and_vars[0]

(<tf.Tensor 'gradients_2/MatMul_grad/tuple/control_dependency_1:0' shape=(784, 100) dtype=float32>,
 <tensorflow.python.ops.variables.Variable at 0x7f0d1b4ed7d0>)

In [17]:
[[tf_core.int_shape(x) for x in w] for w in grads_and_vars]

[[(784, 100), (784, 100)],
 [(100,), (100,)],
 [(100, 10), (100, 10)],
 [(10,), (10,)]]

In [27]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([1, -1, 2, 1])


In [30]:
print(np.convolve(x, y, mode='same'))
print(np.convolve(x, y, mode='valid'))

[1 1 3 6 4]
[3 6]


In [31]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
np.pad(x, ((1, 1), (1, 1)), 'constant')

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  0],
       [ 0,  4,  5,  6,  7,  0],
       [ 0,  8,  9, 10, 11,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [44]:
from keras.layers import Dense, BatchNormalization, Activation
from keras.models import Sequential

In [45]:
model = Sequential()
model.add(Dense(100, input_dim=784, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [46]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 100)               78500     
_________________________________________________________________
dense_6 (Dense)              (None, 10)                1010      
Total params: 79,510.0
Trainable params: 79,510
Non-trainable params: 0.0
_________________________________________________________________


In [47]:
model2 = Sequential()
model2.add(Dense(100, input_dim=784))
model2.add(BatchNormalization())
model2.add(Activation('relu'))
model2.add(Dense(10, activation='softmax'))

In [48]:
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 100)               78500     
_________________________________________________________________
batch_normalization_2 (Batch (None, 100)               400       
_________________________________________________________________
activation_1 (Activation)    (None, 100)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 10)                1010      
Total params: 79,910.0
Trainable params: 79,710.0
Non-trainable params: 200.0
_________________________________________________________________


In [42]:
[w.get_shape().as_list() for w in model2.trainable_weights]

[[784, 100], [100], [100], [100], [100, 10], [10]]