In [1]:
import numpy as np
import tensorflow as tf

In [11]:
def one_hot_encoding(indices, max_index):
    I = np.eye(max_index).astype('float32')
    embedded = tf.nn.embedding_lookup(I, indices)
    embedded_2 = tf.gather(I, indices)
    return embedded, embedded_2

max_index = 10
indices = tf.placeholder(shape=(None, 5), dtype='int32')
embedded, embedded_2 = one_hot_encoding(indices, max_index)

indices_numpy = np.random.randint(0, 10, size=(3, 5))
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
embedded_numpy = sess.run(embedded, feed_dict={indices: indices_numpy})
embedded_2_numpy = sess.run(embedded, feed_dict={indices: indices_numpy})
print(indices_numpy)
print(embedded_numpy.shape)
print(np.all(embedded_numpy == embedded_2_numpy))

[[0 1 2 7 1]
 [7 5 2 9 2]
 [5 3 6 0 4]]
(3, 5, 10)
True


In [8]:
print(embedded_numpy)

[[[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
  [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
  [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
  [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
  [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]]]
