In [1]:
from Teemo.examples.reuters_keras.load_data import reuters_keras
from keras.models import Sequential
from keras.layers import Dense, Activation, LSTM, Embedding
from keras.optimizers import SGD
import numpy as np

Using Theano backend.


In [2]:
train_x, train_y, valid_x, valid_y = reuters_keras(keras_type=True)
train_x = [np.asarray(x) for x in train_x]
train_y = [np.asarray(x) for x in train_y]
valid_x = [np.asarray(x) for x in valid_x]
valid_y = [np.asarray(x) for x in valid_y]
print (len(train_x), len(train_y))
print (train_x[0][:10])

(8982, 8982)
[  1   2   2   8  43  10 447   5  25 207]


In [3]:
max_id = np.max([np.max(x) for x in train_x])
min_id = np.min([np.min(x) for x in train_x])
max_y = np.max(train_y)
voca_size = max_id + 1
n_classes = max_y + 1
word_vec_dim = 100
hidden_dim = 200

In [4]:
model = Sequential()
model.add(Embedding(output_dim=word_vec_dim, input_dim=voca_size))
model.add(LSTM(output_dim=hidden_dim, return_sequences=False))
model.add(Dense(output_dim=n_classes, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.001, momentum=0.), metrics=['accuracy'])

In [ ]:
def train_one_epoch(model, train_x, train_y):
    for x, y in zip(train_x, train_y):
        x = x[np.newaxis, :]
        y = np.eye(n_classes)[y][np.newaxis, :]
        model.train_on_batch(x, y)

def evaluate(model, valid_x, valid_y):
    loss_list = []
    for x, y in zip(valid_x, valid_y):
        x = x[np.newaxis, :]
        y = np.eye(n_classes)[y][np.newaxis, :]
        loss, metric = model.test_on_batch(x, y)
        loss_list.append(loss)
    return np.mean(loss_list)

def train(model, train_x, train_y, valid_x, valid_y):
    n_epoch = 10
    loss_list = []
    for ii in range(n_epoch):
        train_one_epoch(model, train_x, train_y)
        loss = evaluate(model, valid_x, valid_y)
        print ('Epoch: {0}, loss: {1}'.format(ii, loss))
        loss_list.append(loss)
    
train(model, train_x, train_y, valid_x, valid_y)

In [ ]:
dictionary = corpora.Dictionary(texts)
print (dictionary)
print (dictionary.token2id)

In [17]:
dic = corpora.Dictionary([['a', 'b'], ['c', 'd']])
print (dic)
print (dic.token2id)

2016-12-01 13:34:24,252 : INFO : adding document #0 to Dictionary(0 unique tokens: [])
2016-12-01 13:34:24,252 : INFO : built Dictionary(4 unique tokens: [u'a', u'c', u'b', u'd']) from 2 documents (total 4 corpus positions)


Dictionary(4 unique tokens: [u'a', u'c', u'b', u'd'])
{u'a': 0, u'c': 2, u'b': 1, u'd': 3}


In [21]:
new_doc = 'Human computer interaction human'
new_vec = dictionary.doc2bow(new_doc.lower().split())
print (new_vec)

[(1, 1), (2, 2)]


In [23]:
corpus = [dictionary.doc2bow(text) for text in texts]
pprint (corpus)

[[(0, 1), (1, 1), (2, 1)],
 [(1, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1)],
 [(0, 1), (6, 1), (7, 1), (8, 1)],
 [(2, 1), (6, 2), (8, 1)],
 [(3, 1), (4, 1), (7, 1)],
 [(9, 1)],
 [(9, 1), (10, 1)],
 [(9, 1), (10, 1), (11, 1)],
 [(5, 1), (10, 1), (11, 1)]]


In [24]:
print (dictionary.dfs)

{0: 2, 1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 3, 7: 3, 8: 2, 9: 3, 10: 3, 11: 2}


In [34]:
import numpy as np
import gensim
mat = np.random.uniform(size=(4, 3))
corpus = gensim.matutils.Dense2Corpus(mat)
print (mat)
print (corpus)
for doc in corpus:
    print (doc)

[[ 0.30528765  0.13012134  0.46654478]
 [ 0.65625257  0.46661058  0.13246266]
 [ 0.05575696  0.7109175   0.78536732]
 [ 0.5510513   0.30350838  0.07598952]]
[(0, 0.30528765157085835), (1, 0.65625256814444077), (2, 0.055756961103615499), (3, 0.5510513002043429)]
[(0, 0.13012134153175137), (1, 0.46661057708285414), (2, 0.7109174954843972), (3, 0.30350838466174057)]
[(0, 0.46654478016935341), (1, 0.13246266009308361), (2, 0.78536731669087534), (3, 0.07598952416226834)]
